[build]
  command = "npx convex deploy --cmd-url-env-var-name VITE_CONVEX_URL --cmd 'bun run build'"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[context.deploy-preview]
  command = "bun run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
